use yew::prelude::*;
use alert::Alert;

pub struct ApisSettings {}

pub enum Msg {}

impl Component for ApisSettings {
    type Message = Msg;
    type Properties = ();

    fn create(_ctx: &Context<Self>) -> Self {
        ApisSettings {}
    }

    fn update(&mut self, _ctx: &Context<Self>, _msg: Self::Message) -> bool {
        true
    }

    fn changed(&mut self, _ctx: &Context<Self>) -> bool {
        false
    }

    fn view(&self, _ctx: &Context<Self>) -> Html {
        html! {
            <>
                <h1 class="uk-heading-small uk-margin-medium-bottom">{ "API Settings" }</h1>

                <p>{ "Use the Settings tab in the Auth0 Dashboard at Dashboard > Applications > APIs to configure registered APIs that you can consume from your authorized applications. To configure an API's settings, click ... next to an API in the list and select." }
                <b class="td-margin-text">{ "Settings" }</b>
                {"or click the API name. To learn how to create and register an API, read Register APIs."}
                </p>
                <img
                    class="uk-margin-top uk-margin-bottom"
                    src="/assets/apis-settings/dashboard-apis-list.png"
                />

                <div class="uk-margin-large-bottom">
                    <h1 class="td-text-size-large">{ "Settings" }</h1>
                    <p>
                        { "Use the settings on this tab to configure token expiration, role-based access control (RBAC), and other access settings. Click" }
                        <b class="td-margin-text">{ "Save" }</b>
                        { " at the bottom of the tab to save changes." }
                    </p>
                
                </div>

                <div class="uk-margin-large-bottom">
                    <h1 class="td-text-size-large">{ "General Settings" }</h1>
                    <p>
                    { "These fields were set when you initially registered the API, except in the case of the Telkom Domain Management API. You can only modify the" }
                    <b class="td-margin-text">{ "Name" }</b>
                    </p>
                    <img
                    class="uk-margin-top uk-margin-bottom"
                    src="/assets/apis-settings/dashboard-applications-apis-settings-general-settings.png"
                />
                    
                    <ul class="uk-list uk-list-disc">
                        <li>
                            <b class="td-margin-text">
                                { "Id:" }
                            </b>
                            { "A unique alphanumeric string generated by Auth0. This information is read-only, and you will only need it if you will be working directly with Auth0's Management API Resource Servers endpoints." }
                        </li>
                        <li>
                            <b class="td-margin-text">
                                { "Name:" }
                            </b>
                            { "A friendly name for the API. Does not affect any functionality. The following characters are not allowed: < >." }
                        
                        </li>
                        <li>
                            <b class="td-margin-text">
                                { "Identifier:" }
                            </b>
                            { "A unique identifier for your API. This value is set upon API creation and cannot be modified afterward. We recommend using a URL, but this doesn't have to be a publicly available URL; Auth0 will not call your API at all." }
                        </li>
                        
                    </ul>
                </div>

                <div class="uk-margin-large-bottom">
                    <h1 class="td-text-size-large">{ "Token Settings" }</h1>
                    <img
                        class="uk-margin-top uk-margin-bottom"
                        src="/assets/apis-settings/dashboard-applications-apis-settings-token-settings.png"
                    />
                    <ul class="uk-list uk-list-disc">
                    <li>
                        <b class="td-margin-text">
                            { "Token Expiration (Seconds):" }
                        </b>
                        { "The amount of time (in seconds) before the Auth0 Access Token expires. The default value is 86400 seconds (24 hours). The maximum value you can set is 2592000 seconds (30 days)." }
                    </li>
                    <li>
                        <b class="td-margin-text">
                            { "Allow Skipping User Consent:" }
                        </b>
                        { "When this is enabled, the User Consent dialog will not be shown to the end-user when a first-party application requests authorized access against your API. Please note that if the hostname of your application's" }
                        <b class="td-margin-text">{ "callbackURL" }</b>
                        {"is localhost or 127.0.0.1, the consent dialog will always be displayed."}
                    </li>
                    <li>
                        <b class="td-margin-text">
                            { "Signing Algorithm: " }
                        </b>
                        { "The algorithm with which to sign the tokens. The signature is used to verify that the sender of the JWT is who it says it is and to ensure that the message wasn't changed along the way. The available values are HS256 and RS256. When selecting RS256 (recommended), the token will be signed with your tenant's private key. This value is set when your API is created and cannot be modified afterward. To learn more about signing algorithms and how they work in Auth0, read Signing Algorithms." }
                    </li>
                    
                </ul>
                <Alert message={String::from("The signature is part of a JWT. If you are unfamiliar with JWT structure, please see JSON Web Token Structure.")}/>
                </div>

                <div class="uk-margin-large-bottom">
                    <h1 class="td-text-size-large">{ "RBAC Settings" }</h1>
                    <img
                    class="uk-margin-top uk-margin-bottom"
                    src="/assets/apis-settings/dashboard-apis-edit_view-settings_rbac-settings.png"
                />
                <ul class="uk-list uk-list-disc">
                <li>
                    <b class="td-margin-text">
                        { "Enable RBAC:" }
                    </b>
                    { "Enable this setting for RBAC policies to be enforced for the API. To learn more, read Role-Based Access Control and Enable Role-Based Access Control for APIs. For troubleshooting help, review Troubleshoot Role-Based Access Control and Authorization." }
                </li>
                <li>
                    <b class="td-margin-text">
                        { "Add Permissions in the Access Token: " }
                    </b>
                    { "Enable this setting to add the Permissions claim to the access token. This setting is only available if you enable RBAC. You can configure permissions on the Permissions tab." }
                   
                </li>
                </ul>
                </div>

                <div class="uk-margin-large-bottom">
                    <h1 class="td-text-size-large">{ "Access Settings" }</h1>
                    <img
                    class="uk-margin-top uk-margin-bottom"
                    src="/assets/apis-settings/dashboard-applications-apis-settings-access-settings.png"
                />
                <ul class="uk-list uk-list-disc">
                <li>
                    <b class="td-margin-text">
                        { "Allow Skipping User Consent:" }
                    </b>
                    { "Enable this setting for the API to skip user consent for applications flagged as " }
                    <q>{"first party"}</q>
                </li>
                <li>
                    <b class="td-margin-text">
                        { "Allow Offline Access: " }
                    </b>
                    { "Enable this setting to allow applications to ask for refresh tokens for the API." }
                   
                </li>
                </ul>
                </div>

                <div class="uk-margin-large-bottom">
                    <h1 class="td-text-size-large">{ "Permissions" }</h1>
                    <p>
                    { "Use the settings on the " }
                    <b class="td-margin-text">{ "Permissions" }</b>
                    { "  tab to define the permissions (scopes) that the API will use. To learn more, read Add API Permissions and Delete API Permissions." }
                </p>
                <img
                class="uk-margin-top uk-margin-bottom"
                src="/assets/apis-settings/dashboard-applications-apis-permissions.png"
            />
                </div>
                
                <div class="uk-margin-large-bottom">
                <h1 class="td-text-size-large">{ "Machine-to-Machine Applications" }</h1>
                <p>
                { "If you have machine-to-machine applications, they will appear in a list on this tab. Use the toggles to authorize applications in the list. To learn more, read Register Machine-to-Machine Applications." }
                
            </p>
            <img
            class="uk-margin-top uk-margin-bottom"
            src="/assets/apis-settings/dashboard-applications-apis-m2m.png"
        />
            </div>

            <div class="uk-margin-large-bottom">
            <h1 class="td-text-size-large">{ "Test" }</h1>
            <p>
            { "You can choose an application to test with the API. To learn how to create a test machine-to-machine application for Management API testing, read Create Machine-to-Machine Applications for Testing." }
            
            </p>
            <img
               class="uk-margin-top uk-margin-bottom"
               src="/assets/apis-settings/dashboard-applications-apis-test.png"
            />
            </div>

            <div class="uk-margin-large-bottom">
            <h1 class="td-text-size-large">{ "Management API Explorer" }</h1>
            <p>
            { "If you view the" }
            <b class="td-margin-text">{ "Settings" }</b>
            {"for the Auth0 Management API, you will see an additional tab called"}
            <b class="td-margin-text">{ "API Explorer" }</b>
            </p>
            <img
               class="uk-margin-top uk-margin-bottom"
               src="/assets/apis-settings/dashboard-applications-apis-api-explorer.png"
            />
            <p>{"For troubleshooting help, review Check API Calls."}</p>
            </div>   
         
                <div
                    class="uk-margin-large-bottom"
                >
                    <h1 class="td-text-size-large">{ "Learn more" }</h1>
                    <ul class="uk-list uk-list-disc">
                        <li>{ "Register APIs" }</li>
                        <li>{ "Tokens" }</li>
                        <li>{ "Signing Algorithms" }</li>
                        <li>{ "API Scopes" }</li>
                        <li>{ "Configure Logical API for Multiple APIs" }</li>
                        <li>{ "Create Machine-to-Machine Applications for Testing" }</li>
                    </ul>
                </div>
                
            </>
        }
    }
}
